# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1b91caa1a778737c2d43ee6d9997a0ce4fd95354072a739560303d682886763acc8b153f5e96c9036d07ef3e1fb4983d28a8444072f3186e15ddfdbacbc913

test:
  secret_key_base: 8e037ffd0e24f1641a34abe9a63ce8b656f28d122b7f45a2ab6723564740591e9f7d40c17ee306af8b9f4d8a453666e0876d5a27c65b4b11d3be7abbe04979f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
